### PR TITLE
Update use of self in best practices.

### PR DESCRIPTION
**Pull request by roberthein**
Not writing self explicitly is the way to go from now on.

### CODE REVIEW

**Comment by marijnschilling** [comment]
I guess I have to go and try this. Wanted to wait until the next project, but kron seems to stay around for  while.

**Comment by elland** [comment]
@marijnschilling you can try on your next component. Like the count label maybe.

**Comment by marijnschilling** [comment]
But I say merge it! or: self.🚢

**Comment by 3lvis** [comment]
👀 👀 👀 👀 👀 👀 👀 👀 👀

**Comment by elland** [comment]
I don't think we should merge this. We either keep it or remove it and do on a per project basis.

**Comment by marijnschilling** [comment]
Any opinion or idea on how to deal with this on running projects @roberthein?

**Comment by roberthein** [comment]
Running projects last forever and double standards is hard to work with in this case. So we need to migrate existing code as soon as we can.

**Comment by roberthein** [comment]
There is no need to hurry though, just when there is time and resources to do it.

**Comment by yuliaveres** [comment]
👏  🍎  😃

**Comment by roberthein** [comment]
I'm merging this. Let's all think about how and when to update the projects we are currently working on. 🚀 🚀 🚀

**Pull request merged**
