### PR TITLE
Add reasoning behind controller naming

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by elland** [comment]
⛵️ it

**Comment by 3lvis** [comment]
@heumn that's the reason :)

**Comment by heumn** [comment]
> Because naming anything else a `Controller` in general is a bad idea and should have another name instead.

Isnt that really just an argument that is not backed by any reasoning? This playbook is really good, but this part as well as the usage of "ItemCell" vs "ItemTableViewCell" confuses most people I have shared this with.

**Comment by 3lvis** [comment]
@heumn I think is a good argument. Could you suggest anything named "Controller" that falls beyond the UIViewController subclassing pattern?

I think I could give you a reason why that's wrong. Otherwise I'll make sure we include a note for that.

**Comment by elland** [comment]
Controller is a super general term that doesn't describe anything specific. The only place we use it is as a view controller subclass, because that's how Apple and MVC refers to them. 

Regarding `TableViewCell`, on that one I'm also not super convinced.

**Comment by 3lvis** [comment]
I agree with the cell part. Is not 100% set in stone, that's one of the reasons why is not included in the playbook. So far my reasoning is that, it shouldn't matter if a cell is part of a tableview controller or a collection view controller in the filename. Internally the only difference is the subclass that they inherit from. Ideally, I should be able to switch from a table to a collection and the other way without the need of renaming my files. Reducing the chances of conflicts and making it easier to refactor since you don't have to change every single object name.

**Comment by heumn** [comment]
>  @heumn I think is a good argument. Could you suggest anything named "Controller" that falls beyond the UIViewController subclassing pattern?

I understand your argument as this:
- You should never name things controllers.
- The only acceptable controller is a ViewController.

Following this logic, Controllers = ViewController, thus we can drop the View prefix (?)

To me, "ItemController" adds too little information. On what level am I controlling an "item"? What am I doing with it?

Compare that to:
UIAlertController // Ok, we are a controller of alerts
UIViewController // Ok, we are a controlling views
UINavigationController // Ok, we are a controller of navigation

I am not arguing that naming things a controller/manager is generally a good practice but removing specifications about what a controller is controlling looks a bit strange to me. Why? Mainly it follows the general thought I have always been told (and agree with) that I will spend most of my time reading my own and colleagues code and I would rather have a more verbose and clear (controller) name, than a less verbose one.

> Regarding TableViewCell, on that one I'm also not super convinced.

That is the one that bothers me the most and naming UICollectionCells and UITableViewCells "ItemCell" is even more confusing to me than the controller/viewcontroller scenario. Since I know from experience that you prefer to not name things controller (a good idea) thus reasoning with your code when you follow that practice is easier. But ItemCell? 🤔 

But again, I applaud you guys for this guide and I think I read it twice per day 👏

**Comment by 3lvis** [comment]
@heumn 

UIAlertController is not "UIAlertViewController"
UINavigationController is not "UINavigationViewController"

And so on.

**Comment by 3lvis** [comment]
@heumn Why you would need a cell to have "TableViewCell" or "CollectionViewCell" in the name? What difference would it make?

**Comment by heumn** [comment]
> UIAlertController is not "UIAlertViewController"
> UINavigationController is not "UINavigationViewController"

Sorry, I did not understand what you mean. I am arguing that all of these are perfectly fine class names.

UIAlertController // Ok, we are a controller of alerts
UIViewController // Ok, we are a controlling views
UINavigationController // Ok, we are a controller of navigation
UIMenuController // Ok, we are a controller of menu
UIPrintInteractionController // Ok, we are a controller of print interaction

How would you name these classes?

> The only place we use it is as a view controller subclass, ...

This also sounds almost like "any `Context`-containing class name is wrong because the only context sort of stuff that we use is NSManagedObjectContext"

or "NSIndexSet is a wrong class name because we use NSCharacterSet only in our code and you don't need any other "set" thing other than NSCharacterSet ever"

That logic does not fly with me :)

> I should be able to switch from a table to a collection and the other way without the need of renaming my files

Following this logic it would makes sense to name all cells as Object because being "too" specific in class naming leads to extra work related to renaming due to changes in implementation, i.e. we should probably admit that both "Item" and "Cell" are overly specific too. 

>  What would you need a cell to have "TableViewCell" or "CollectionViewCell" in the name? What difference it would make?

I presume you meant *why here

Because I want to be explicit about what it is. Now based on "how it might change if the implementation change.

I do not really care as I just know that I am not the only one feeling this way and I thought I would at least vent my thoughts on the matter.

**Comment by elland** [comment]
@heum he's pointing out that you just argued against yourself by giving example of view controllers that don't have view controller on their class names. 😅

**Comment by heumn** [comment]
Hah, got it.. Tired today... Yeah, I chose bad examples. The two latter ones still stand :)

> UIMenuController // Ok, we are a controller of menu
> UIPrintInteractionController // Ok, we are a controller of print interaction

**Comment by 3lvis** [comment]
Pretty much a similar conversation happened here.

**Comment by 3lvis** [comment]
Pretty much a similar conversation happened here.

https://github.com/hyperoslo/iOS-playbook/issues/130

**Comment by 3lvis** [comment]
Regarding cell naming. What I mentioned about renaming is a benefit of doing it this way, not the main reason on why we do it like this.

I don't see the need on prefixing a cell with the container type, it doesn't change anything in my implementation or makes it clearer in any way, it's the same, and if it's the same, I don't see the reason on having it.

**Comment by heumn** [comment]
> Pretty much a similar conversation happened here.
> 
> hyperoslo/iOS-playbook#130

Thanks for the link. I must agree there are some valid points in that argument.

> I don't see the need on prefixing a cell with the container type, it doesn't change anything in my implementation or makes it clearer in any way, it's the same, and if it's the same, I don't see the reason on having it.

But it is not the same?

A UITableViewCell is in no way the same as a UICollectionViewCell? And they would end up being named the same. MyObjectCell. That is my main concern about this. Thus a reason not to name it like that.

What is the benefit of naming things MyObjectCell?

**Comment by 3lvis** [comment]
You have to start simple then grow in complexity, for me the same applies for naming. It can't be called `View` because it's part of a reusable/recyclable list of items, it's meant to be a container of an object that is part of a list, so it has to be a cell. Then it wouldn't be "RecipeView" it would be "RecipeCell", then you ask next but it's part of a collection view or a table view, then you'll add "RecipeTableViewCell" or "RecipeCollectionViewCell", but I wouldn't go that far because I don't see the reason why I would have to do that. What benefit does it give? You shouldn't be more explicit than what you have to be. Only grow in complexity when you can't keep it simple.

As an exercise try this in a pet project or whatever and you'll see that you don't need to make cell classes more explicit than just MyObjectCell. At least that is my experience so far.

**Comment by heumn** [comment]
> You have to start simple then grow in complexity, for me the same applies for naming. 

Agree

> It can't be called View because it's part of a reusable/recyclable list of items, it's meant to be a container of an object that is part of a list, so it has to be a cell.

Agree

> then you ask next but it's part of a collection view or a table view, then you'll add "RecipeTableViewCell" or "RecipeCollectionViewCell", but I wouldn't go that far because I don't see the reason why I would have to do that.

You do not see a reason. I do. Drawing a line there. Thanks for taking the time to explain your thoughts on the matter!

**Comment by 3lvis** [comment]
@heumn

> A UITableViewCell is in no way the same as a UICollectionViewCell? And they would end up being named the same. MyObjectCell. That is my main concern about this. Thus a reason not to name it like that.

You don't name your model that subclasses of NSManagedObject different than one that doesn't, they get the same treatment. 

``` swift
class Ingredient: NSManagedObject {
}
```

``` swift
struct Ingredient {
}
```

Same logic applies here.

You don't do:

``` swift
class CoreDataIngredient: NSManagedObject {
}
```

``` swift
class IngredientManagedObject: NSManagedObject {
}
```

**Comment by heumn** [comment]
> You don't name your model that subclasses of NSManagedObject different than one that doesn't, they get the same treatment.

True. But would you care if the model was a subclass of NSManagedObject when using it? 🤔

**Comment by 3lvis** [comment]
I think I will know that is a subclass of `NSManagedObject` for what's needed and I wouldn't need the class to have the `ManagedObject` suffix, same as `TableViewCell` and `CollectionViewCell`.

Caring might be subjective, could you elaborate your last question? I don't follow what you're trying to clarify.

**Comment by heumn** [comment]
Why I ask that question is because I can think of scenarios where I would care if a class was a subclass of a UITableViewCell or UICollectionViewCell. I would (normally) not care what was backing the Model

But I often forget things, thus the question :)

**Comment by 3lvis** [comment]
I think you might need the context in most cases but maybe is not relevant to have it in the class name the same why you don't prefix all your subclasses. Maybe we could clarify if you can share some of your scenarios.

**Comment by 3lvis** [comment]
I think you might need the context in most cases but maybe is not relevant to have it in the class name for the same reason why you don't suffix all your subclasses. Maybe we could clarify if you can share some of your scenarios.

**Comment by heumn** [comment]
I am putting my involvement to rest here :) Thanks for explaining your thoughts on the matter

**Comment by 3lvis** [comment]
Thanks being so patient and trying to understand why we do what we do. I'm still gonna be curious on your reasons on why is critical to have "RecipeTableViewCell" or "RecipeCollectionViewCell", instead of just using "RecipeCell". Hopefully we'll get time to talk about it.

**Pull request merged**
