### PR TITLE
remove self usage as a requirement

### PR DESCRIPTION
**Pull request by heumn**
Briefly discussed with @yuliaveres and seems like this is a rule you are not enforcing anymore. sooo... time to remove it! 🎉

### CODE REVIEW

**Comment by yuliaveres** [comment]
Great ❤️

**Review by yuliaveres — APPROVED** [review]

**Review by roberthein — APPROVED** [review]
😘

**Comment by elland** [comment]
😭 I'll miss you, old friend.

**Review by elland — APPROVED** [review]

**Comment by marijnschilling** [comment]
Seems to be missing the update for swift lint, there self is still inserted

**Review by roberthein — CHANGES_REQUESTED** [review]
Can you also remove:
https://github.com/bakkenbaeck/iOS-handbook/blob/master/BEST_PRACTICES.md#use-of-self

**Review by roberthein — APPROVED** [review]
I see it's already gone 👌

**Pull request merged**
