### PR TITLE
Add guidelines for commented code

### PR DESCRIPTION
**Pull request by marijnschilling**
For now i just copied the things from android, all suggestions welcome! 🙌

### CODE REVIEW

**Review by yuliaveres — APPROVED** [review]
Great !

**Comment by elland** [comment]
I have a small exception in my day-to-day: I sometimes have commited commented out code that I use for testing/debugging. It's usually easier than using a bunch of `#DEBUG-X` constants, I can just uncomment the lines I need. 🤔

**Comment by yuliaveres** [comment]
@Elland , right, but only you use it :D
create a named stash which you can always apply ? or branch ?

**Comment by elland** [comment]
That's a sure way to spend time dealing with merge conflicts. 😅 But if you have a better way to approach it I'm all ears. 👍

**Comment by yuliaveres** [comment]
i dnt think i have any idea for you :/
but in general i think we should not allow comments being pushed for the testing purpose

**Comment by elland** [comment]
I agree, I avoid it as well. Suggestion: no commented out code to master?

**Comment by yuliaveres** [comment]
100% agree

**Review by elland — APPROVED** [review]

**Pull request merged**
