### PR TITLE
Update to only use self when required #selfxit

### PR DESCRIPTION
**Pull request by 3lvis**
In codebases with many developers and no linter sometimes we use self and sometimes we don't. To make it easier to keep consistency in what we write, I think is better if we only use `self.` when it's required by the compiler, for example in usage inside closures or when assigning values to a variable that has the same name.

### CODE REVIEW

**Comment by marijnschilling** [comment]
Hard one... Because it was in the playBook rules I started (to at least try and) use it all the time. 

The main reason why I like it is for unwrapping optionals. You don't have to get all creative with names but can just say: if let myValue = self.myValue

And it does make things easier in the way that you immediately see if it's a property or just a local var. 

What would be the reason why you would not use self?

**Comment by 3lvis** [comment]
You can still do the unwrapping without self usage.

``` swift
if let myValue = myValue
```

**Comment by 3lvis** [comment]
Mainly that I've noticed a lot of inconsistency in `self` usage, and might be easier to not use it specially since it's not required and Apple's guidelines point to only use it when needed.

**Comment by marijnschilling** [comment]
Hmmm I think it's mainly more clear to use self. So I'd vote for use it. 
(we can have a referendum about it, how exciting!)

**Comment by 3lvis** [comment]
Swift Evolution Proposal where they rejected this and their reasons:

https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160104/005478.html

**Comment by elland** [comment]
I agree with @marijnschilling, it's clearer when you're accessing a local variable v. a property if self is always present. After reading this swift evolution proposal, I agree even more that it should be enforced by the compiler. Same for functions.

**Comment by 3lvis** [comment]
Sounds good. I'll close this, feel free to reopen or make a new PR if you change your mind :)

**Pull request closed without merging**
