### PR TITLE
[WIP] GETTING_STARTED

### PR DESCRIPTION
**Pull request by 3lvis**
A document that will help you to go through what's needed when starting a new project. 

- Document Realm usage
- Document Carthage usage
- Expand releases document to include App Store and TestFlight and Enterprise #42
- Add a rule to disable merge commits to the GitHub guidelines
- Document SwiftFormat usage

### CODE REVIEW

**Comment by elland** [comment]
More info?

**Comment by 3lvis** [comment]
@Elland Added some info.

**Comment by elland** [comment]
Nice! We should forecast a day or so to get this all done quickly at once, what do you think?

**Comment by 3lvis** [comment]
@Elland That's the plan! Tuesday next week 💥

**Comment by 3lvis** [comment]
Linked to some of the challenges here https://github.com/bakkenbaeck/iOS-playbook/issues/46

**Comment by elland** [comment]
I think we can clear up a bit, since we don't use Realm anymore, for instance.

**Comment by elland** [comment]
Worth finishing this tomorrow with @roberthein. ✨

**Comment by elland** [comment]
@yuliaveres @roberthein feedback here?

**Pull request closed without merging**
