### PR TITLE
Update project structure

### PR DESCRIPTION
**Pull request by 3lvis**
## Fetchers to APIClient

A fetcher _fetches_, meaning it's main purpose is to retrieve data, meanwhile our use case is also to send data to the server. APIClient works for all our current scenarios.

### CODE REVIEW

**Comment by elland** [comment]
How is a client different from a manager? 🤔

**Comment by 3lvis** [comment]
@elland APIClient is a known term to be used in this cases. Also is not a manager which is a singleton.

**Comment by elland** [comment]
Since when is `manager` implied to be singleton? 🤔 Also, can you give me some examples of code where something is a client? 😄

**Comment by 3lvis** [comment]
@Elland I'all take some time later to look some examples. If you google APIClient you'll find more about the pattern, I found this, might help a bit.

https://ffeathers.wordpress.com/2015/10/25/what-is-an-api-client-library/

**Comment by elland** [comment]
To me it makes more sense if we can make it obvious that the name is supposed to be tweaked per project. Like `PinboardCLient`, `JottaCliet`, etc… So that `APIClient` is only the generic superclass, not to be used directly. What do you think?

**Comment by 3lvis** [comment]
I would say not every singleton is a Manager, but a Manager would most likely be a singleton, not really important for this conversation, though.

**Comment by 3lvis** [comment]
@Elland I think we discussed this at some point. It probably makes sense for apps that use different backends, for most apps where we only interact with one being specific shouldn't be needed. But for apps that have more than one (quite rare) we should use what you mentioned.

**Comment by 3lvis** [comment]
We need to reach an agreement for this today. Fetcher doesn't seem like the best name for this.

**Comment by elland** [comment]
I'm fine with APIClient. But I was also fine with Fetcher. It's also what Apple used in some of their sample code.

**Comment by marijnschilling** [comment]
I'm fine with APIClient, found Fetcher confusing in the beginning indeed. I'm also not opposed using the name of the project in the name, I think this will make it more clear that it is a project specific class. Not like `Networking` which is meant to be mostly untouched (right?). Fetcher/APIClient is 100% project specific. `NodeAPIClient`. :)

**Comment by elland** [comment]
@marijnschilling this is better! I like it.

**Comment by 3lvis** [comment]
Looks like we agreed :D

**Comment by elland** [comment]
👏 Already using this for <-redacted->! 🗡

**Pull request merged**
